services:
  - type: web
    name: zentra
    env: static
    plan: free
    staticPublishPath: site
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
